In [16]:
# STRINGS USING SPLIT

val = 'a,b, dumbo'


split_array = val.split(',')

print(split_array)

pieces = [x.strip() for x in val.split(',')]

print(pieces)


['a', 'b', ' dumbo']
['a', 'b', 'dumbo']


In [17]:
# STRINGS USING JOIN

joined_string = ",".join(pieces)    
print(joined_string)

a,b,dumbo


In [18]:
#STRING USING REPLACE

replaced_string = joined_string.replace(",", ":")

print(replaced_string)

a:b:dumbo


In [19]:
#REGULAR EXPRESSIONS

import re

text = "foo bar baz qux"

print(text)

results = re.split(r"\s+", text)

print(results)


foo bar baz qux
['foo', 'bar', 'baz', 'qux']


In [20]:
rege = re.compile(r"a")

rege.findall(text)

['a', 'a']

In [21]:
#STRING  FUNCTIONS IN PANDAS
import numpy as np
import pandas as pd

data ={"Dave": "dave@google.com", "Steve" : "steve@gmail.com", "Rob" : "rob@google.com", "Wes" : np.nan}

print(type(data))

data = pd.Series(data)

print(type(data))

print(data)


<class 'dict'>
<class 'pandas.core.series.Series'>
Dave     dave@google.com
Steve    steve@gmail.com
Rob       rob@google.com
Wes                  NaN
dtype: object


In [22]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [25]:


data.str.contains("Steve")  

Dave     False
Steve    False
Rob      False
Wes        NaN
dtype: object

In [26]:
data_as_string = data.astype(str)

print(data_as_string)
print(type(data_as_string))

Dave     dave@google.com
Steve    steve@gmail.com
Rob       rob@google.com
Wes                  nan
dtype: object
<class 'pandas.core.series.Series'>


In [ ]:
#  CATAGORICAL DATA
#NOTE THAT THE SEED NUMBER IS USED FOR REPRODUCIBILITY. IF I WANT TO USE THE SAME "RANDOM" NUMBERS 
# AGAIN, I SHOULD USE THE SAME SEED NUMBER


fruits =['apples', 'oranges', 'pears', 'bananas']

N = len(fruits)

rng = np.random.default_rng(seed=42)


results_rng = rng.integers(0, 10, size=(N, 4))

print(results_rng)

results = pd.DataFrame(results_rng, columns=fruits)

print(results)

[[0 7 6 4]
 [4 8 0 6]
 [2 0 5 9]
 [7 7 7 7]]
   apples  oranges  pears  bananas
0       0        7      6        4
1       4        8      0        6
2       2        0      5        9
3       7        7      7        7
